# Generated by Django 5.2.1 on 2025-08-30 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_category_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postanalytics',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_analytics', to='blog.post'),
        ),
    ]
