# Generated by Django 5.2.1 on 2026-01-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_useraccount_login_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller'), ('admin', 'Admin'), ('moderator', 'Moderator'), ('helper', 'Helper'), ('editor', 'Editor')], default='customer', max_length=20),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
